os: Visual Studio 2015

version: 0.3.{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

# Before build
install:
- ps: >-
    ./scripts/paket.exe restore
- ps: >-
    ./scripts/SetReleaseVersion.ps1

# # Do the build
# before_build:
# - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
# - ps: >-
#     ./scripts/SetPackageVersions.ps1

build_script:
  - cmd: build.cmd BuildPackage

artifacts:
  - path: nuget/*.nupkg
  - name: NuGet packages

# build:
#   verbosity: minimal
#   project: Nap.sln
#   publish_nuget: true
#   publish_nuget_symbols: true

#---------------------------------#
#      general configuration      #
#---------------------------------#
branches:
  only:
    - master
    - develop

configuration: Release

environment:
  COVERALLS_REPO_TOKEN:
    secure: CT+N3PO6ROIpHj/yozEuEVDnbL1+OjJ3TynGgXXfhc4AGqyrJ074rkJNxyHkEDA2

#---------------------------------#
#        test configuration       #
#---------------------------------#

test_script:
  - echo Skipping default test runner.
# test:
#   assemblies:
#     - '**\*.Tests.dll'
# after_test:
#   - cmd: .\packages\OpenCover\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" -targetargs:".\Nap.Tests\bin\Release\Nap.Tests.dll .\Nap.Tests\bin\Release\Nap.Immutable.Tests.dll" -output:coverage.xml
#   - cmd: .\packages\coveralls.io\tools\coveralls.net.exe --opencover coverage.xml

#---------------------------------#
#     deployment configuration    #
#---------------------------------#
deploy:
  - provider: NuGet
    artifact: /.*\.nupkg/
    api_key:
      secure: ELbN5jzU0YJ7y3qZsMv6OTGmVVkVgBIaUVkWu2GhamhjCTnYQzNs+VSoXdZWs7Jw
    on:
      branch: master
      appveyor_repo_tag: true

#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:
  - provider: Webhook
    url: https://zapier.com/hooks/catch/25chs9/
