os: Visual Studio 2015 CTP 6

version: 0.2.{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
install:
- nuget restore
- ps: >-
    ./scripts/SetReleaseVersion.ps1
before_build:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
build:
  verbosity: minimal
after_test:
- ps: >-
    ./scripts/BuildPackages.ps1

#---------------------------------#
#      general configuration      #
#---------------------------------#
branches:
  only:
    - master
    - develop

configuration: Release

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
artifacts:
  - path: Nap\*.nupkg
  - path: Nap.Configuration\*.nupkg
  - path: Nap.Html\*.nupkg

#---------------------------------#
#     deployment configuration    #
#---------------------------------#
deploy:
  provider: NuGet
  api_key: 
    secure: ELbN5jzU0YJ7y3qZsMv6OTGmVVkVgBIaUVkWu2GhamhjCTnYQzNs+VSoXdZWs7Jw
  artifact: /.*\.nupkg/
  on:
    branch: master
    appveyor_repo_tag: true

#---------------------------------#
#         notifications           #
#---------------------------------#
notifications:
  - provider: Webhook
    url: https://www.notifymyandroid.com/publicapi/notify?apikey= 
    headers:
      apikey:
        secure: zXzU/JnZoKz24WoaVoPMmQrXi+3LjiDCC1Uvr02alLswLnXURcsyVhzukG2aSpRbJ1KYkyb9glEVDVURzv9j2Q==
      application: appveyor_repo_tag
      event: "Nap build {status}"
      description: "{message}"
      priority: 1
      url: "{commitId}"